all: ese650-quchao-proj1.tex
	rubber -d $<

edit:
	texmaker  ese650-quchao-proj1.tex &

test:
	evince ese650-quchao-proj1.pdf &

clean:
	rm -f *.aux *.log *.out *.pdf *.pdfsync *.synctex.gz *.blg *.bbl
